import { Resend } from 'resend';
import type { FBGroup, IGTarget, TradeIGTarget, ColdEmailStats as InstantlyStats } from './gtm-supabase.js';

export interface BriefData {
  date: Date;
  yesterday: {
    trialStarts: number;
    trialStartsBreakdown: Record<string, number>;
    paidConversions: number;
    revenueAdded: number;
    runningTotal: number;
    goalTotal: number;
    goalDeadline: string;
  };
  coldEmail: InstantlyStats;
  igTargets: IGTarget[];
  tradeIgTargets: TradeIGTarget[];
  fbGroups: FBGroup[];
  anomalies: string[];
  founderContentPrompts: string[];
}

export interface RenderedBrief {
  subject: string;
  html: string;
  text: string;
}

export function renderBrief(data: BriefData): RenderedBrief {
  const dateStr = data.date.toLocaleDateString('en-AU', {
    weekday: 'long',
    day: 'numeric',
    month: 'short',
  });
  const pace = Math.round((data.yesterday.runningTotal / data.yesterday.goalTotal) * 100);

  const text = `
GOOD MORNING ATTICUS — Flynn GTM brief — ${dateStr}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📊 YESTERDAY
  Trial starts:        ${data.yesterday.trialStarts}
    └ cold email: ${data.yesterday.trialStartsBreakdown.coldEmail ?? 0}, IG DM: ${data.yesterday.trialStartsBreakdown.igDm ?? 0}, organic: ${data.yesterday.trialStartsBreakdown.organic ?? 0}, paid: ${data.yesterday.trialStartsBreakdown.paidAds ?? 0}
  Paid conversions:    ${data.yesterday.paidConversions}
  Revenue added:       $${data.yesterday.revenueAdded.toFixed(2)}
  Running total:       ${data.yesterday.runningTotal} / ${data.yesterday.goalTotal}   (${pace}% to goal · deadline ${data.yesterday.goalDeadline})

📧 COLD EMAIL — ${data.coldEmail.sentLast24h} sent yesterday, ${data.coldEmail.repliesLast24h} replies
  Hot replies overnight: ${data.coldEmail.hotReplies}
  Bounce rate (7d):      ${(data.coldEmail.bounceRateLast7d * 100).toFixed(1)}%
  Warmup buffer:         ${Math.round(data.coldEmail.warmupBuffer * 100)}%
  → Open Instantly: https://app.instantly.ai/app/campaigns

📱 INSTAGRAM DMs (partnerships) — ${data.igTargets.length} prefilled
${data.igTargets
  .map(
    (t, i) =>
      `  ${(i + 1).toString().padStart(2, ' ')}. ${t.handle.padEnd(28, ' ')} ${String(t.followerCount).padStart(6, ' ')} followers · ${t.industry.padEnd(8)} ${t.region}   [${t.suggestedScript}]   ${t.profileUrl}`,
  )
  .join('\n')}

🛠 TRADE IG SALES — ${data.tradeIgTargets.length} prefilled (AI-written DMs ready to copy)
${data.tradeIgTargets
  .map((t, i) => {
    const snippet = t.aiMessage.replace(/\s+/g, ' ').slice(0, 120);
    const meta = `${t.followerCount.toLocaleString()} followers · ${t.trade || 'trade'} · ${t.city || 'AU'}`;
    return `  ${(i + 1).toString().padStart(2, ' ')}. @${t.handle} — ${t.businessName || '(no name)'}
       ${meta}
       "${snippet}…"
       ${t.profileUrl}`;
  })
  .join('\n')}

👥 FACEBOOK GROUPS — ${data.fbGroups.length} to engage
${data.fbGroups
  .map(
    (g, i) =>
      `  ${i + 1}. ${g.name} (${g.memberCount.toLocaleString()} members)
     Last posted: ${g.lastPostedAt ?? 'never'}
     Suggested: ${g.suggestedPostType}
     Open: ${g.url}`,
  )
  .join('\n\n')}

⚠️  NEEDS YOUR ATTENTION
${data.anomalies.length === 0 ? '  (none)' : data.anomalies.map((a) => `  - ${a}`).join('\n')}

💡 FOUNDER CONTENT PROMPTS (3 posts/week target)
${data.founderContentPrompts.map((p) => `  - ${p}`).join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Brief generated by gtm-automation/morning-brief.ts at ${data.date.toISOString()}
`.trim();

  const html = textToHtml(text);

  return {
    subject: `Flynn GTM — ${dateStr} — ${data.yesterday.runningTotal}/${data.yesterday.goalTotal} (${pace}%)`,
    html,
    text,
  };
}

function textToHtml(text: string): string {
  // Wrap in monospace block — keeps the ASCII layout
  const escaped = text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');

  // Make https://... clickable
  const linked = escaped.replace(
    /(https?:\/\/[^\s)]+)/g,
    '<a href="$1" style="color:#ff4500">$1</a>',
  );

  return `<pre style="font-family: ui-monospace, Menlo, monospace; font-size: 13px; line-height: 1.5; white-space: pre-wrap;">${linked}</pre>`;
}

export async function sendBrief(brief: RenderedBrief): Promise<void> {
  const apiKey = required('RESEND_API_KEY');
  const from = required('BRIEF_FROM_EMAIL');
  const to = required('BRIEF_TO_EMAIL');

  const resend = new Resend(apiKey);
  const result = await resend.emails.send({
    from: `Flynn Brief <${from}>`,
    to: [to],
    subject: brief.subject,
    html: brief.html,
    text: brief.text,
  });

  if (result.error) throw new Error(`Resend send failed: ${result.error.message}`);
}

function required(name: string): string {
  const v = process.env[name];
  if (!v) throw new Error(`Missing env ${name}`);
  return v;
}
