#!/usr/bin/env bash
# Install a macOS login item that opens the Flynn GTM dashboard in Chrome
# automatically when you log in.
#
# Run once: bash gtm-automation/scripts/install-login-item.sh
# Uninstall: bash gtm-automation/scripts/install-login-item.sh --uninstall

set -euo pipefail

DASHBOARD_URL="file:///Users/atticus/FlynnAIapp/gtm-automation/morning-dashboard/morning.html"
PLIST_LABEL="com.flynn.gtm.openOnLogin"
PLIST_PATH="$HOME/Library/LaunchAgents/${PLIST_LABEL}.plist"
SCRIPT_PATH="$HOME/Library/Application Support/flynn-gtm/open-dashboard.sh"

if [[ "${1:-}" == "--uninstall" ]]; then
  echo "Uninstalling Flynn GTM login item..."
  launchctl unload "$PLIST_PATH" 2>/dev/null || true
  rm -f "$PLIST_PATH" "$SCRIPT_PATH"
  echo "Done. The dashboard will no longer auto-open at login."
  exit 0
fi

echo "Installing Flynn GTM login item..."
echo "  Dashboard: $DASHBOARD_URL"
echo "  Plist:     $PLIST_PATH"

# 1. Create the open script
mkdir -p "$(dirname "$SCRIPT_PATH")"
cat > "$SCRIPT_PATH" <<EOF
#!/usr/bin/env bash
# Open the Flynn GTM dashboard in Chrome at login.
# Auto-generated by install-login-item.sh — edit if you want.
sleep 5  # give Chrome a moment to launch its own startup tabs
/usr/bin/open -a "Google Chrome" "$DASHBOARD_URL"
EOF
chmod +x "$SCRIPT_PATH"

# 2. Create the launchd plist
cat > "$PLIST_PATH" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${PLIST_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${SCRIPT_PATH}</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>StandardOutPath</key>
  <string>/tmp/flynn-gtm-open.log</string>
  <key>StandardErrorPath</key>
  <string>/tmp/flynn-gtm-open.err</string>
</dict>
</plist>
EOF

# 3. Load it
launchctl unload "$PLIST_PATH" 2>/dev/null || true
launchctl load "$PLIST_PATH"

echo ""
echo "✅ Done. Next time you log in, Chrome will open to:"
echo "   $DASHBOARD_URL"
echo ""
echo "To uninstall: bash $0 --uninstall"
echo "To test now (without logging out):"
echo "   open -a 'Google Chrome' '$DASHBOARD_URL'"
