# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  'iPhone 16 Pro',
  'iPhone 16 Pro Max',
  'iPhone 16e',
  'iPad Pro 13-inch (M4)'
])

languages([
  'en-US'
])

# The name of the scheme which contains the UI Tests
scheme('FlynnAI')

# Where should the resulting screenshots be stored?
output_directory('../screenshots')

# Use a stable DerivedData location so Xcode doesn't try to write to
# fastlane's ephemeral /var/folders path (which was triggering mkstemp
# failures during Swift compilation).
derived_data_path('../build/snapshot-derived-data')

# remove the '#' to clear all previously generated screenshots before creating new ones
# clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
# override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
